// Расширенная база продуктов с КБЖУ на 100г
// Источники: Calorizator.ru, FatSecret, USDA

export const productsDatabase = [
  // Крупы и злаки
  { id: 1, name: 'Овсянка (сухая)', calories: 366, protein: 12, fat: 6, carbs: 60, category: 'Крупы' },
  { id: 2, name: 'Овсянка на воде', calories: 88, protein: 3, fat: 2, carbs: 15, category: 'Крупы' },
  { id: 3, name: 'Овсянка на молоке 2.5%', calories: 102, protein: 4, fat: 3, carbs: 16, category: 'Крупы' },
  { id: 4, name: 'Гречка (сухая)', calories: 343, protein: 13, fat: 3, carbs: 72, category: 'Крупы' },
  { id: 5, name: 'Гречка варёная', calories: 110, protein: 4, fat: 1, carbs: 21, category: 'Крупы' },
  { id: 6, name: 'Рис белый (сухой)', calories: 365, protein: 7, fat: 1, carbs: 80, category: 'Крупы' },
  { id: 7, name: 'Рис белый варёный', calories: 130, protein: 3, fat: 0, carbs: 28, category: 'Крупы' },
  { id: 8, name: 'Рис бурый (сухой)', calories: 337, protein: 7, fat: 3, carbs: 77, category: 'Крупы' },
  { id: 9, name: 'Рис бурый варёный', calories: 112, protein: 3, fat: 1, carbs: 24, category: 'Крупы' },
  { id: 10, name: 'Рис басмати (сухой)', calories: 355, protein: 8, fat: 1, carbs: 78, category: 'Крупы' },
  { id: 11, name: 'Макароны (сухие)', calories: 350, protein: 12, fat: 2, carbs: 75, category: 'Крупы' },
  { id: 12, name: 'Макароны варёные', calories: 115, protein: 4, fat: 1, carbs: 25, category: 'Крупы' },
  { id: 13, name: 'Макароны из твёрдых сортов', calories: 345, protein: 13, fat: 1, carbs: 73, category: 'Крупы' },
  { id: 14, name: 'Киноа (сухая)', calories: 368, protein: 14, fat: 6, carbs: 64, category: 'Крупы' },
  { id: 15, name: 'Киноа варёная', calories: 120, protein: 4, fat: 2, carbs: 21, category: 'Крупы' },
  { id: 16, name: 'Пшено (сухое)', calories: 348, protein: 11, fat: 3, carbs: 67, category: 'Крупы' },
  { id: 17, name: 'Пшённая каша', calories: 92, protein: 3, fat: 1, carbs: 17, category: 'Крупы' },
  { id: 18, name: 'Перловка (сухая)', calories: 324, protein: 9, fat: 1, carbs: 74, category: 'Крупы' },
  { id: 19, name: 'Перловка варёная', calories: 109, protein: 3, fat: 0, carbs: 23, category: 'Крупы' },
  { id: 20, name: 'Ячневая крупа', calories: 322, protein: 10, fat: 1, carbs: 72, category: 'Крупы' },
  { id: 21, name: 'Манка (сухая)', calories: 333, protein: 10, fat: 1, carbs: 73, category: 'Крупы' },
  { id: 22, name: 'Манная каша на молоке', calories: 98, protein: 3, fat: 2, carbs: 16, category: 'Крупы' },
  { id: 23, name: 'Кукурузная крупа', calories: 337, protein: 8, fat: 1, carbs: 75, category: 'Крупы' },
  { id: 24, name: 'Хлеб цельнозерновой', calories: 250, protein: 8, fat: 4, carbs: 45, category: 'Хлеб' },
  { id: 25, name: 'Хлеб белый', calories: 265, protein: 8, fat: 3, carbs: 50, category: 'Хлеб' },
  { id: 26, name: 'Хлеб чёрный (бородинский)', calories: 208, protein: 7, fat: 1, carbs: 41, category: 'Хлеб' },
  { id: 27, name: 'Хлеб ржаной', calories: 190, protein: 6, fat: 1, carbs: 39, category: 'Хлеб' },
  { id: 28, name: 'Лаваш армянский', calories: 275, protein: 9, fat: 1, carbs: 56, category: 'Хлеб' },
  { id: 29, name: 'Лаваш тонкий', calories: 280, protein: 8, fat: 2, carbs: 58, category: 'Хлеб' },
  { id: 30, name: 'Батон нарезной', calories: 265, protein: 8, fat: 3, carbs: 51, category: 'Хлеб' },
  
  // Мясо и птица
  { id: 31, name: 'Куриная грудка (сырая)', calories: 113, protein: 23, fat: 2, carbs: 0, category: 'Мясо' },
  { id: 32, name: 'Куриная грудка варёная', calories: 165, protein: 31, fat: 4, carbs: 0, category: 'Мясо' },
  { id: 33, name: 'Куриная грудка жареная', calories: 195, protein: 29, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 34, name: 'Куриная грудка на гриле', calories: 172, protein: 32, fat: 4, carbs: 0, category: 'Мясо' },
  { id: 35, name: 'Куриное бедро (сырое)', calories: 177, protein: 18, fat: 11, carbs: 0, category: 'Мясо' },
  { id: 36, name: 'Куриное бедро жареное', calories: 210, protein: 20, fat: 14, carbs: 0, category: 'Мясо' },
  { id: 37, name: 'Куриные крылья', calories: 220, protein: 18, fat: 16, carbs: 0, category: 'Мясо' },
  { id: 38, name: 'Куриная печень', calories: 136, protein: 20, fat: 6, carbs: 0, category: 'Мясо' },
  { id: 39, name: 'Куриное сердце', calories: 159, protein: 16, fat: 10, carbs: 0, category: 'Мясо' },
  { id: 40, name: 'Индейка филе', calories: 115, protein: 24, fat: 2, carbs: 0, category: 'Мясо' },
  { id: 41, name: 'Индейка голень', calories: 142, protein: 20, fat: 6, carbs: 0, category: 'Мясо' },
  { id: 42, name: 'Индейка бедро', calories: 144, protein: 20, fat: 7, carbs: 0, category: 'Мясо' },
  { id: 43, name: 'Говядина постная', calories: 158, protein: 22, fat: 7, carbs: 0, category: 'Мясо' },
  { id: 44, name: 'Говядина вырезка', calories: 113, protein: 21, fat: 3, carbs: 0, category: 'Мясо' },
  { id: 45, name: 'Говядина лопатка', calories: 180, protein: 19, fat: 11, carbs: 0, category: 'Мясо' },
  { id: 46, name: 'Говядина грудинка', calories: 275, protein: 18, fat: 22, carbs: 0, category: 'Мясо' },
  { id: 47, name: 'Говяжья печень', calories: 125, protein: 20, fat: 4, carbs: 0, category: 'Мясо' },
  { id: 48, name: 'Говяжий язык', calories: 173, protein: 16, fat: 12, carbs: 0, category: 'Мясо' },
  { id: 49, name: 'Телятина', calories: 105, protein: 20, fat: 2, carbs: 0, category: 'Мясо' },
  { id: 50, name: 'Свинина постная', calories: 190, protein: 20, fat: 11, carbs: 0, category: 'Мясо' },
  { id: 51, name: 'Свинина вырезка', calories: 142, protein: 20, fat: 6, carbs: 0, category: 'Мясо' },
  { id: 52, name: 'Свинина шея', calories: 265, protein: 16, fat: 22, carbs: 0, category: 'Мясо' },
  { id: 53, name: 'Свинина грудинка', calories: 375, protein: 14, fat: 35, carbs: 0, category: 'Мясо' },
  { id: 54, name: 'Свиная печень', calories: 130, protein: 20, fat: 4, carbs: 0, category: 'Мясо' },
  { id: 55, name: 'Баранина постная', calories: 160, protein: 20, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 56, name: 'Баранина лопатка', calories: 210, protein: 18, fat: 15, carbs: 0, category: 'Мясо' },
  { id: 57, name: 'Кролик', calories: 156, protein: 21, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 58, name: 'Фарш говяжий', calories: 215, protein: 18, fat: 15, carbs: 0, category: 'Мясо' },
  { id: 59, name: 'Фарш свиной', calories: 265, protein: 16, fat: 22, carbs: 0, category: 'Мясо' },
  { id: 60, name: 'Фарш куриный', calories: 143, protein: 17, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 61, name: 'Фарш индейки', calories: 150, protein: 19, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 62, name: 'Бекон', calories: 540, protein: 13, fat: 54, carbs: 0, category: 'Мясо' },
  { id: 63, name: 'Ветчина', calories: 145, protein: 18, fat: 8, carbs: 0, category: 'Мясо' },
  { id: 64, name: 'Колбаса варёная (докторская)', calories: 255, protein: 12, fat: 23, carbs: 0, category: 'Мясо' },
  { id: 65, name: 'Колбаса копчёная', calories: 360, protein: 16, fat: 32, carbs: 0, category: 'Мясо' },
  { id: 66, name: 'Сосиски', calories: 265, protein: 11, fat: 24, carbs: 2, category: 'Мясо' },
  { id: 67, name: 'Сардельки', calories: 305, protein: 11, fat: 28, carbs: 2, category: 'Мясо' },
  
  // Рыба и морепродукты
  { id: 68, name: 'Лосось', calories: 208, protein: 20, fat: 13, carbs: 0, category: 'Рыба' },
  { id: 69, name: 'Лосось на гриле', calories: 206, protein: 22, fat: 12, carbs: 0, category: 'Рыба' },
  { id: 70, name: 'Сёмга', calories: 219, protein: 20, fat: 15, carbs: 0, category: 'Рыба' },
  { id: 71, name: 'Форель', calories: 148, protein: 20, fat: 7, carbs: 0, category: 'Рыба' },
  { id: 72, name: 'Тунец консервированный в собственном соку', calories: 116, protein: 26, fat: 1, carbs: 0, category: 'Рыба' },
  { id: 73, name: 'Тунец консервированный в масле', calories: 192, protein: 23, fat: 10, carbs: 0, category: 'Рыба' },
  { id: 74, name: 'Тунец свежий', calories: 144, protein: 23, fat: 5, carbs: 0, category: 'Рыба' },
  { id: 75, name: 'Тилапия', calories: 96, protein: 20, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 76, name: 'Минтай', calories: 72, protein: 16, fat: 1, carbs: 0, category: 'Рыба' },
  { id: 77, name: 'Треска', calories: 82, protein: 18, fat: 1, carbs: 0, category: 'Рыба' },
  { id: 78, name: 'Треска запечённая', calories: 95, protein: 19, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 79, name: 'Хек', calories: 86, protein: 17, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 80, name: 'Пикша', calories: 73, protein: 17, fat: 0, carbs: 0, category: 'Рыба' },
  { id: 81, name: 'Сельдь', calories: 161, protein: 18, fat: 9, carbs: 0, category: 'Рыба' },
  { id: 82, name: 'Сельдь солёная', calories: 217, protein: 18, fat: 16, carbs: 0, category: 'Рыба' },
  { id: 83, name: 'Скумбрия', calories: 262, protein: 18, fat: 21, carbs: 0, category: 'Рыба' },
  { id: 84, name: 'Скумбрия копчёная', calories: 221, protein: 22, fat: 14, carbs: 0, category: 'Рыба' },
  { id: 85, name: 'Камбала', calories: 90, protein: 18, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 86, name: 'Палтус', calories: 186, protein: 19, fat: 12, carbs: 0, category: 'Рыба' },
  { id: 87, name: 'Судак', calories: 84, protein: 18, fat: 1, carbs: 0, category: 'Рыба' },
  { id: 88, name: 'Щука', calories: 82, protein: 18, fat: 1, carbs: 0, category: 'Рыба' },
  { id: 89, name: 'Карп', calories: 125, protein: 18, fat: 5, carbs: 0, category: 'Рыба' },
  { id: 90, name: 'Сазан', calories: 97, protein: 18, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 91, name: 'Окунь морской', calories: 95, protein: 18, fat: 2, carbs: 0, category: 'Рыба' },
  { id: 92, name: 'Креветки', calories: 99, protein: 24, fat: 1, carbs: 0, category: 'Морепродукты' },
  { id: 93, name: 'Креветки варёные', calories: 95, protein: 21, fat: 1, carbs: 0, category: 'Морепродукты' },
  { id: 94, name: 'Кальмары', calories: 92, protein: 18, fat: 2, carbs: 0, category: 'Морепродукты' },
  { id: 95, name: 'Мидии', calories: 77, protein: 12, fat: 2, carbs: 3, category: 'Морепродукты' },
  { id: 96, name: 'Устрицы', calories: 68, protein: 7, fat: 3, carbs: 4, category: 'Морепродукты' },
  { id: 97, name: 'Краб', calories: 87, protein: 18, fat: 1, carbs: 0, category: 'Морепродукты' },
  { id: 98, name: 'Крабовые палочки', calories: 73, protein: 6, fat: 1, carbs: 10, category: 'Морепродукты' },
  { id: 99, name: 'Морской коктейль', calories: 85, protein: 15, fat: 2, carbs: 2, category: 'Морепродукты' },
  { id: 100, name: 'Икра красная', calories: 263, protein: 32, fat: 15, carbs: 0, category: 'Морепродукты' },
  { id: 101, name: 'Икра чёрная', calories: 235, protein: 28, fat: 13, carbs: 0, category: 'Морепродукты' },
  { id: 102, name: 'Икра минтая', calories: 132, protein: 28, fat: 2, carbs: 0, category: 'Морепродукты' },
  
  // Молочные продукты
  { id: 103, name: 'Творог 0%', calories: 72, protein: 18, fat: 0, carbs: 2, category: 'Молочное' },
  { id: 104, name: 'Творог 1%', calories: 81, protein: 17, fat: 1, carbs: 2, category: 'Молочное' },
  { id: 105, name: 'Творог 5%', calories: 121, protein: 17, fat: 5, carbs: 2, category: 'Молочное' },
  { id: 106, name: 'Творог 9%', calories: 159, protein: 14, fat: 9, carbs: 2, category: 'Молочное' },
  { id: 107, name: 'Творог 18%', calories: 236, protein: 14, fat: 18, carbs: 2, category: 'Молочное' },
  { id: 108, name: 'Творог обезжиренный', calories: 72, protein: 18, fat: 0, carbs: 2, category: 'Молочное' },
  { id: 109, name: 'Творожная масса ванильная', calories: 342, protein: 8, fat: 23, carbs: 27, category: 'Молочное' },
  { id: 110, name: 'Сырники', calories: 220, protein: 13, fat: 12, carbs: 15, category: 'Молочное' },
  { id: 111, name: 'Молоко 0.5%', calories: 35, protein: 3, fat: 0, carbs: 5, category: 'Молочное' },
  { id: 112, name: 'Молоко 1.5%', calories: 45, protein: 3, fat: 1, carbs: 5, category: 'Молочное' },
  { id: 113, name: 'Молоко 2.5%', calories: 52, protein: 3, fat: 2, carbs: 5, category: 'Молочное' },
  { id: 114, name: 'Молоко 3.2%', calories: 60, protein: 3, fat: 3, carbs: 5, category: 'Молочное' },
  { id: 115, name: 'Молоко 6%', calories: 85, protein: 3, fat: 6, carbs: 5, category: 'Молочное' },
  { id: 116, name: 'Кефир 0%', calories: 30, protein: 3, fat: 0, carbs: 4, category: 'Молочное' },
  { id: 117, name: 'Кефир 1%', calories: 40, protein: 3, fat: 1, carbs: 4, category: 'Молочное' },
  { id: 118, name: 'Кефир 2.5%', calories: 53, protein: 3, fat: 2, carbs: 4, category: 'Молочное' },
  { id: 119, name: 'Кефир 3.2%', calories: 60, protein: 3, fat: 3, carbs: 4, category: 'Молочное' },
  { id: 120, name: 'Ряженка 1%', calories: 40, protein: 3, fat: 1, carbs: 4, category: 'Молочное' },
  { id: 121, name: 'Ряженка 2.5%', calories: 54, protein: 3, fat: 2, carbs: 4, category: 'Молочное' },
  { id: 122, name: 'Ряженка 4%', calories: 67, protein: 3, fat: 4, carbs: 4, category: 'Молочное' },
  { id: 123, name: 'Йогурт натуральный 0%', calories: 35, protein: 4, fat: 0, carbs: 4, category: 'Молочное' },
  { id: 124, name: 'Йогурт натуральный 2%', calories: 50, protein: 4, fat: 2, carbs: 4, category: 'Молочное' },
  { id: 125, name: 'Йогурт греческий 0%', calories: 59, protein: 10, fat: 0, carbs: 4, category: 'Молочное' },
  { id: 126, name: 'Йогурт греческий 2%', calories: 75, protein: 9, fat: 2, carbs: 5, category: 'Молочное' },
  { id: 127, name: 'Йогурт питьевый', calories: 85, protein: 3, fat: 2, carbs: 14, category: 'Молочное' },
  { id: 128, name: 'Сметана 10%', calories: 115, protein: 3, fat: 10, carbs: 3, category: 'Молочное' },
  { id: 129, name: 'Сметана 15%', calories: 162, protein: 3, fat: 15, carbs: 3, category: 'Молочное' },
  { id: 130, name: 'Сметана 20%', calories: 206, protein: 3, fat: 20, carbs: 3, category: 'Молочное' },
  { id: 131, name: 'Сметана 25%', calories: 248, protein: 3, fat: 25, carbs: 3, category: 'Молочное' },
  { id: 132, name: 'Сливки 10%', calories: 118, protein: 3, fat: 10, carbs: 4, category: 'Молочное' },
  { id: 133, name: 'Сливки 20%', calories: 206, protein: 3, fat: 20, carbs: 4, category: 'Молочное' },
  { id: 134, name: 'Сливки 33%', calories: 322, protein: 3, fat: 33, carbs: 4, category: 'Молочное' },
  { id: 135, name: 'Сыр чеддер', calories: 403, protein: 25, fat: 33, carbs: 1, category: 'Молочное' },
  { id: 136, name: 'Сыр моцарелла', calories: 280, protein: 22, fat: 20, carbs: 2, category: 'Молочное' },
  { id: 137, name: 'Сыр пармезан', calories: 431, protein: 38, fat: 29, carbs: 4, category: 'Молочное' },
  { id: 138, name: 'Сыр гауда', calories: 356, protein: 25, fat: 27, carbs: 2, category: 'Молочное' },
  { id: 139, name: 'Сыр эмменталь', calories: 380, protein: 29, fat: 28, carbs: 0, category: 'Молочное' },
  { id: 140, name: 'Сыр российский', calories: 363, protein: 24, fat: 29, carbs: 0, category: 'Молочное' },
  { id: 141, name: 'Сыр пошехонский', calories: 350, protein: 26, fat: 26, carbs: 0, category: 'Молочное' },
  { id: 142, name: 'Сыр адыгейский', calories: 240, protein: 19, fat: 18, carbs: 0, category: 'Молочное' },
  { id: 143, name: 'Сыр сулугуни', calories: 285, protein: 20, fat: 22, carbs: 0, category: 'Молочное' },
  { id: 144, name: 'Сыр брынза', calories: 262, protein: 18, fat: 20, carbs: 0, category: 'Молочное' },
  { id: 145, name: 'Сыр фета', calories: 243, protein: 14, fat: 19, carbs: 4, category: 'Молочное' },
  { id: 146, name: 'Сыр творожный', calories: 172, protein: 12, fat: 13, carbs: 3, category: 'Молочное' },
  { id: 147, name: 'Сыр плавленый', calories: 285, protein: 14, fat: 24, carbs: 4, category: 'Молочное' },
  { id: 148, name: 'Сыр тофу', calories: 76, protein: 8, fat: 5, carbs: 2, category: 'Молочное' },
  { id: 149, name: 'Яйцо куриное (1 шт, 55г)', calories: 85, protein: 7, fat: 6, carbs: 0, category: 'Молочное' },
  { id: 150, name: 'Яйцо куриное (100г)', calories: 155, protein: 13, fat: 11, carbs: 1, category: 'Молочное' },
  { id: 151, name: 'Яичный белок (100г)', calories: 52, protein: 11, fat: 0, carbs: 1, category: 'Молочное' },
  { id: 152, name: 'Яичный желток (100г)', calories: 352, protein: 16, fat: 31, carbs: 1, category: 'Молочное' },
  { id: 153, name: 'Яйцо перепелиное (1 шт)', calories: 17, protein: 1, fat: 1, carbs: 0, category: 'Молочное' },
  { id: 154, name: 'Омлет натуральный', calories: 155, protein: 10, fat: 12, carbs: 2, category: 'Молочное' },
  { id: 155, name: 'Омлет с сыром', calories: 195, protein: 12, fat: 15, carbs: 3, category: 'Молочное' },
  { id: 156, name: 'Яичница глазунья', calories: 180, protein: 12, fat: 14, carbs: 1, category: 'Молочное' },
  
  // Овощи
  { id: 157, name: 'Огурцы', calories: 15, protein: 1, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 158, name: 'Помидоры', calories: 18, protein: 1, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 159, name: 'Помидоры черри', calories: 18, protein: 1, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 160, name: 'Брокколи', calories: 34, protein: 3, fat: 0, carbs: 7, category: 'Овощи' },
  { id: 161, name: 'Брокколи варёная', calories: 35, protein: 2, fat: 0, carbs: 7, category: 'Овощи' },
  { id: 162, name: 'Цветная капуста', calories: 25, protein: 2, fat: 0, carbs: 5, category: 'Овощи' },
  { id: 163, name: 'Цветная капуста варёная', calories: 23, protein: 2, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 164, name: 'Капуста белокочанная', calories: 25, protein: 2, fat: 0, carbs: 5, category: 'Овощи' },
  { id: 165, name: 'Капуста пекинская', calories: 16, protein: 1, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 166, name: 'Капуста краснокочанная', calories: 31, protein: 2, fat: 0, carbs: 6, category: 'Овощи' },
  { id: 167, name: 'Морковь', calories: 41, protein: 1, fat: 0, carbs: 10, category: 'Овощи' },
  { id: 168, name: 'Морковь варёная', calories: 25, protein: 1, fat: 0, carbs: 5, category: 'Овощи' },
  { id: 169, name: 'Свёкла', calories: 43, protein: 2, fat: 0, carbs: 10, category: 'Овощи' },
  { id: 170, name: 'Свёкла варёная', calories: 44, protein: 2, fat: 0, carbs: 10, category: 'Овощи' },
  { id: 171, name: 'Перец болгарский красный', calories: 27, protein: 1, fat: 0, carbs: 6, category: 'Овощи' },
  { id: 172, name: 'Перец болгарский зелёный', calories: 20, protein: 1, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 173, name: 'Перец болгарский жёлтый', calories: 27, protein: 1, fat: 0, carbs: 6, category: 'Овощи' },
  { id: 174, name: 'Картофель', calories: 77, protein: 2, fat: 0, carbs: 17, category: 'Овощи' },
  { id: 175, name: 'Картофель варёный', calories: 82, protein: 2, fat: 0, carbs: 17, category: 'Овощи' },
  { id: 176, name: 'Картофельное пюре', calories: 105, protein: 2, fat: 3, carbs: 16, category: 'Овощи' },
  { id: 177, name: 'Картофель фри', calories: 312, protein: 4, fat: 15, carbs: 41, category: 'Овощи' },
  { id: 178, name: 'Лук репчатый', calories: 40, protein: 1, fat: 0, carbs: 9, category: 'Овощи' },
  { id: 179, name: 'Лук зелёный', calories: 19, protein: 1, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 180, name: 'Лук-порей', calories: 61, protein: 2, fat: 0, carbs: 14, category: 'Овощи' },
  { id: 181, name: 'Чеснок', calories: 149, protein: 6, fat: 0, carbs: 33, category: 'Овощи' },
  { id: 182, name: 'Кабачки', calories: 24, protein: 1, fat: 0, carbs: 5, category: 'Овощи' },
  { id: 183, name: 'Кабачки жареные', calories: 85, protein: 1, fat: 6, carbs: 7, category: 'Овощи' },
  { id: 184, name: 'Баклажаны', calories: 25, protein: 1, fat: 0, carbs: 6, category: 'Овощи' },
  { id: 185, name: 'Баклажаны жареные', calories: 95, protein: 1, fat: 7, carbs: 7, category: 'Овощи' },
  { id: 186, name: 'Тыква', calories: 26, protein: 1, fat: 0, carbs: 7, category: 'Овощи' },
  { id: 187, name: 'Тыква запечённая', calories: 45, protein: 1, fat: 0, carbs: 11, category: 'Овощи' },
  { id: 188, name: 'Шпинат', calories: 23, protein: 3, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 189, name: 'Щавель', calories: 22, protein: 2, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 190, name: 'Салат айсберг', calories: 14, protein: 1, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 191, name: 'Салат листовой', calories: 15, protein: 1, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 192, name: 'Салат руккола', calories: 25, protein: 3, fat: 1, carbs: 2, category: 'Овощи' },
  { id: 193, name: 'Сельдерей', calories: 16, protein: 1, fat: 0, carbs: 3, category: 'Овощи' },
  { id: 194, name: 'Спаржа', calories: 20, protein: 2, fat: 0, carbs: 4, category: 'Овощи' },
  { id: 195, name: 'Стручковая фасоль', calories: 31, protein: 2, fat: 0, carbs: 7, category: 'Овощи' },
  { id: 196, name: 'Зелёный горошек', calories: 81, protein: 5, fat: 0, carbs: 14, category: 'Овощи' },
  { id: 197, name: 'Кукуруза консервированная', calories: 119, protein: 3, fat: 1, carbs: 24, category: 'Овощи' },
  { id: 198, name: 'Грибы белые', calories: 34, protein: 3, fat: 1, carbs: 2, category: 'Овощи' },
  { id: 199, name: 'Грибы шампиньоны', calories: 27, protein: 4, fat: 1, carbs: 0, category: 'Овощи' },
  { id: 200, name: 'Грибы вешенки', calories: 33, protein: 3, fat: 0, carbs: 6, category: 'Овощи' },
  { id: 201, name: 'Грибы опята', calories: 22, protein: 2, fat: 1, carbs: 1, category: 'Овощи' },
  { id: 202, name: 'Грибы лисички', calories: 19, protein: 2, fat: 1, carbs: 1, category: 'Овощи' },
  { id: 203, name: 'Грибы жареные', calories: 95, protein: 4, fat: 7, carbs: 5, category: 'Овощи' },
  { id: 204, name: 'Икра кабачковая', calories: 83, protein: 1, fat: 6, carbs: 7, category: 'Овощи' },
  { id: 205, name: 'Икра баклажанная', calories: 80, protein: 2, fat: 5, carbs: 7, category: 'Овощи' },
  
  // Фрукты
  { id: 206, name: 'Яблоко', calories: 52, protein: 0, fat: 0, carbs: 14, category: 'Фрукты' },
  { id: 207, name: 'Яблоко зелёное', calories: 47, protein: 0, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 208, name: 'Яблоко красное', calories: 55, protein: 0, fat: 0, carbs: 14, category: 'Фрукты' },
  { id: 209, name: 'Банан', calories: 89, protein: 1, fat: 0, carbs: 23, category: 'Фрукты' },
  { id: 210, name: 'Апельсин', calories: 47, protein: 1, fat: 0, carbs: 12, category: 'Фрукты' },
  { id: 211, name: 'Грейпфрут', calories: 42, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 212, name: 'Грейпфрут красный', calories: 42, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 213, name: 'Мандарин', calories: 53, protein: 1, fat: 0, carbs: 13, category: 'Фрукты' },
  { id: 214, name: 'Лимон', calories: 29, protein: 1, fat: 0, carbs: 9, category: 'Фрукты' },
  { id: 215, name: 'Лайм', calories: 30, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 216, name: 'Виноград', calories: 67, protein: 1, fat: 0, carbs: 17, category: 'Фрукты' },
  { id: 217, name: 'Виноград зелёный', calories: 69, protein: 1, fat: 0, carbs: 18, category: 'Фрукты' },
  { id: 218, name: 'Виноград красный', calories: 70, protein: 1, fat: 0, carbs: 18, category: 'Фрукты' },
  { id: 219, name: 'Клубника', calories: 32, protein: 1, fat: 0, carbs: 8, category: 'Фрукты' },
  { id: 220, name: 'Земляника', calories: 41, protein: 1, fat: 0, carbs: 9, category: 'Фрукты' },
  { id: 221, name: 'Малина', calories: 52, protein: 1, fat: 1, carbs: 12, category: 'Фрукты' },
  { id: 222, name: 'Черника', calories: 57, protein: 1, fat: 0, carbs: 14, category: 'Фрукты' },
  { id: 223, name: 'Голубика', calories: 57, protein: 1, fat: 0, carbs: 14, category: 'Фрукты' },
  { id: 224, name: 'Смородина чёрная', calories: 44, protein: 1, fat: 0, carbs: 10, category: 'Фрукты' },
  { id: 225, name: 'Смородина красная', calories: 43, protein: 1, fat: 0, carbs: 10, category: 'Фрукты' },
  { id: 226, name: 'Крыжовник', calories: 45, protein: 1, fat: 0, carbs: 10, category: 'Фрукты' },
  { id: 227, name: 'Вишня', calories: 52, protein: 1, fat: 0, carbs: 12, category: 'Фрукты' },
  { id: 228, name: 'Черешня', calories: 50, protein: 1, fat: 0, carbs: 12, category: 'Фрукты' },
  { id: 229, name: 'Слива', calories: 46, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 230, name: 'Абрикос', calories: 48, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 231, name: 'Персик', calories: 39, protein: 1, fat: 0, carbs: 10, category: 'Фрукты' },
  { id: 232, name: 'Нектарин', calories: 44, protein: 1, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 233, name: 'Груша', calories: 57, protein: 0, fat: 0, carbs: 15, category: 'Фрукты' },
  { id: 234, name: 'Айва', calories: 57, protein: 0, fat: 0, carbs: 15, category: 'Фрукты' },
  { id: 235, name: 'Хурма', calories: 70, protein: 1, fat: 0, carbs: 18, category: 'Фрукты' },
  { id: 236, name: 'Гранат', calories: 83, protein: 2, fat: 1, carbs: 19, category: 'Фрукты' },
  { id: 237, name: 'Киви', calories: 61, protein: 1, fat: 1, carbs: 15, category: 'Фрукты' },
  { id: 238, name: 'Ананас', calories: 50, protein: 0, fat: 0, carbs: 13, category: 'Фрукты' },
  { id: 239, name: 'Манго', calories: 60, protein: 1, fat: 0, carbs: 15, category: 'Фрукты' },
  { id: 240, name: 'Папайя', calories: 43, protein: 0, fat: 0, carbs: 11, category: 'Фрукты' },
  { id: 241, name: 'Авокадо', calories: 160, protein: 2, fat: 15, carbs: 9, category: 'Фрукты' },
  { id: 242, name: 'Кокос', calories: 354, protein: 3, fat: 33, carbs: 15, category: 'Фрукты' },
  { id: 243, name: 'Дыня', calories: 34, protein: 1, fat: 0, carbs: 8, category: 'Фрукты' },
  { id: 244, name: 'Арбуз', calories: 30, protein: 1, fat: 0, carbs: 8, category: 'Фрукты' },
  { id: 245, name: 'Финики', calories: 282, protein: 2, fat: 0, carbs: 75, category: 'Фрукты' },
  { id: 246, name: 'Инжир', calories: 74, protein: 1, fat: 0, carbs: 19, category: 'Фрукты' },
  { id: 247, name: 'Курага', calories: 215, protein: 5, fat: 0, carbs: 51, category: 'Фрукты' },
  { id: 248, name: 'Чернослив', calories: 240, protein: 2, fat: 0, carbs: 58, category: 'Фрукты' },
  { id: 249, name: 'Изюм', calories: 264, protein: 3, fat: 0, carbs: 66, category: 'Фрукты' },
  { id: 250, name: 'Бананы сушёные', calories: 346, protein: 4, fat: 2, carbs: 84, category: 'Фрукты' },
  
  // Орехи и семена
  { id: 251, name: 'Миндаль', calories: 579, protein: 21, fat: 50, carbs: 22, category: 'Орехи' },
  { id: 252, name: 'Миндаль жареный', calories: 607, protein: 22, fat: 54, carbs: 20, category: 'Орехи' },
  { id: 253, name: 'Грецкий орех', calories: 654, protein: 15, fat: 65, carbs: 14, category: 'Орехи' },
  { id: 254, name: 'Фундук', calories: 628, protein: 15, fat: 61, carbs: 17, category: 'Орехи' },
  { id: 255, name: 'Кешью', calories: 553, protein: 18, fat: 44, carbs: 30, category: 'Орехи' },
  { id: 256, name: 'Кешью жареный', calories: 574, protein: 18, fat: 46, carbs: 30, category: 'Орехи' },
  { id: 257, name: 'Арахис', calories: 567, protein: 26, fat: 49, carbs: 16, category: 'Орехи' },
  { id: 258, name: 'Арахис жареный', calories: 585, protein: 27, fat: 49, carbs: 16, category: 'Орехи' },
  { id: 259, name: 'Фисташки', calories: 560, protein: 20, fat: 45, carbs: 27, category: 'Орехи' },
  { id: 260, name: 'Фисташки жареные', calories: 572, protein: 21, fat: 46, carbs: 26, category: 'Орехи' },
  { id: 261, name: 'Бразильский орех', calories: 656, protein: 14, fat: 66, carbs: 12, category: 'Орехи' },
  { id: 262, name: 'Пекан', calories: 691, protein: 9, fat: 72, carbs: 14, category: 'Орехи' },
  { id: 263, name: 'Макадамия', calories: 718, protein: 8, fat: 76, carbs: 14, category: 'Орехи' },
  { id: 264, name: 'Кедровый орех', calories: 673, protein: 14, fat: 68, carbs: 13, category: 'Орехи' },
  { id: 265, name: 'Семечки подсолнечника', calories: 584, protein: 21, fat: 51, carbs: 20, category: 'Орехи' },
  { id: 266, name: 'Семечки жареные', calories: 601, protein: 20, fat: 53, carbs: 20, category: 'Орехи' },
  { id: 267, name: 'Семечки тыквенные', calories: 559, protein: 30, fat: 49, carbs: 11, category: 'Орехи' },
  { id: 268, name: 'Кунжут', calories: 573, protein: 18, fat: 50, carbs: 23, category: 'Орехи' },
  { id: 269, name: 'Лён семена', calories: 534, protein: 18, fat: 42, carbs: 29, category: 'Орехи' },
  { id: 270, name: 'Чиа семена', calories: 486, protein: 17, fat: 31, carbs: 42, category: 'Орехи' },
  
  // Масла
  { id: 271, name: 'Масло оливковое', calories: 884, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 272, name: 'Масло подсолнечное', calories: 884, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 273, name: 'Масло сливочное', calories: 717, protein: 1, fat: 81, carbs: 1, category: 'Масла' },
  { id: 274, name: 'Масло сливочное 82%', calories: 748, protein: 1, fat: 82, carbs: 1, category: 'Масла' },
  { id: 275, name: 'Масло топлёное', calories: 885, protein: 0, fat: 99, carbs: 0, category: 'Масла' },
  { id: 276, name: 'Масло кокосовое', calories: 862, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 277, name: 'Масло льняное', calories: 884, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 278, name: 'Масло кунжутное', calories: 884, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 279, name: 'Масло арахисовое', calories: 884, protein: 0, fat: 100, carbs: 0, category: 'Масла' },
  { id: 280, name: 'Майонез', calories: 680, protein: 0, fat: 75, carbs: 4, category: 'Масла' },
  { id: 281, name: 'Майонез лёгкий', calories: 360, protein: 1, fat: 35, carbs: 8, category: 'Масла' },
  { id: 282, name: 'Маргарин', calories: 717, protein: 0, fat: 80, carbs: 1, category: 'Масла' },
  
  // Бобовые
  { id: 283, name: 'Чечевица (сухая)', calories: 353, protein: 25, fat: 1, carbs: 63, category: 'Бобовые' },
  { id: 284, name: 'Чечевица варёная', calories: 116, protein: 9, fat: 0, carbs: 20, category: 'Бобовые' },
  { id: 285, name: 'Чечевица красная', calories: 314, protein: 24, fat: 1, carbs: 60, category: 'Бобовые' },
  { id: 286, name: 'Чечевица зелёная', calories: 323, protein: 25, fat: 1, carbs: 59, category: 'Бобовые' },
  { id: 287, name: 'Нут (сухой)', calories: 364, protein: 19, fat: 6, carbs: 61, category: 'Бобовые' },
  { id: 288, name: 'Нут варёный', calories: 164, protein: 9, fat: 3, carbs: 27, category: 'Бобовые' },
  { id: 289, name: 'Фасоль (сухая)', calories: 347, protein: 22, fat: 1, carbs: 63, category: 'Бобовые' },
  { id: 290, name: 'Фасоль варёная', calories: 127, protein: 8, fat: 0, carbs: 23, category: 'Бобовые' },
  { id: 291, name: 'Фасоль красная', calories: 333, protein: 23, fat: 1, carbs: 61, category: 'Бобовые' },
  { id: 292, name: 'Фасоль белая', calories: 333, protein: 23, fat: 1, carbs: 61, category: 'Бобовые' },
  { id: 293, name: 'Фасоль стручковая', calories: 31, protein: 2, fat: 0, carbs: 7, category: 'Бобовые' },
  { id: 294, name: 'Горох (сухой)', calories: 341, protein: 23, fat: 2, carbs: 60, category: 'Бобовые' },
  { id: 295, name: 'Горох варёный', calories: 115, protein: 8, fat: 0, carbs: 20, category: 'Бобовые' },
  { id: 296, name: 'Горошек зелёный', calories: 81, protein: 5, fat: 0, carbs: 14, category: 'Бобовые' },
  { id: 297, name: 'Соя (сухая)', calories: 446, protein: 36, fat: 20, carbs: 30, category: 'Бобовые' },
  { id: 298, name: 'Соевое мясо', calories: 296, protein: 52, fat: 1, carbs: 19, category: 'Бобовые' },
  { id: 299, name: 'Тофу', calories: 76, protein: 8, fat: 5, carbs: 2, category: 'Бобовые' },
  { id: 300, name: 'Темпе', calories: 193, protein: 19, fat: 11, carbs: 9, category: 'Бобовые' },
  
  // Соусы и приправы
  { id: 301, name: 'Кетчуп', calories: 112, protein: 1, fat: 0, carbs: 27, category: 'Соусы' },
  { id: 302, name: 'Майонез', calories: 680, protein: 0, fat: 75, carbs: 4, category: 'Соусы' },
  { id: 303, name: 'Горчица', calories: 162, protein: 6, fat: 10, carbs: 13, category: 'Соусы' },
  { id: 304, name: 'Хрен', calories: 56, protein: 1, fat: 1, carbs: 12, category: 'Соусы' },
  { id: 305, name: 'Соевый соус', calories: 53, protein: 8, fat: 0, carbs: 5, category: 'Соусы' },
  { id: 306, name: 'Уксус столовый', calories: 11, protein: 0, fat: 0, carbs: 1, category: 'Соусы' },
  { id: 307, name: 'Уксус яблочный', calories: 22, protein: 0, fat: 0, carbs: 1, category: 'Соусы' },
  { id: 308, name: 'Винный уксус', calories: 19, protein: 0, fat: 0, carbs: 1, category: 'Соусы' },
  { id: 309, name: 'Бальзамический уксус', calories: 88, protein: 0, fat: 0, carbs: 17, category: 'Соусы' },
  { id: 310, name: 'Томатная паста', calories: 102, protein: 5, fat: 0, carbs: 23, category: 'Соусы' },
  { id: 311, name: 'Томатный соус', calories: 70, protein: 2, fat: 1, carbs: 15, category: 'Соусы' },
  { id: 312, name: 'Аджика', calories: 59, protein: 2, fat: 2, carbs: 9, category: 'Соусы' },
  { id: 313, name: 'Ткемали', calories: 55, protein: 1, fat: 0, carbs: 13, category: 'Соусы' },
  { id: 314, name: 'Сацибели', calories: 75, protein: 1, fat: 3, carbs: 12, category: 'Соусы' },
  { id: 315, name: 'Сметанный соус', calories: 155, protein: 3, fat: 13, carbs: 7, category: 'Соусы' },
  { id: 316, name: 'Грибной соус', calories: 95, protein: 2, fat: 7, carbs: 8, category: 'Соусы' },
  { id: 317, name: 'Сырный соус', calories: 210, protein: 5, fat: 18, carbs: 10, category: 'Соусы' },
  { id: 318, name: 'Чесночный соус', calories: 185, protein: 2, fat: 17, carbs: 8, category: 'Соусы' },
  { id: 319, name: 'Тартар', calories: 460, protein: 2, fat: 48, carbs: 8, category: 'Соусы' },
  { id: 320, name: 'Цезарь', calories: 485, protein: 3, fat: 50, carbs: 9, category: 'Соусы' },
  { id: 321, name: 'Барбекю', calories: 172, protein: 1, fat: 1, carbs: 41, category: 'Соусы' },
  { id: 322, name: 'Терияки', calories: 130, protein: 6, fat: 0, carbs: 26, category: 'Соусы' },
  { id: 323, name: 'Сладкий чили', calories: 195, protein: 1, fat: 0, carbs: 49, category: 'Соусы' },
  { id: 324, name: 'Соль', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Соусы' },
  { id: 325, name: 'Сахар', calories: 387, protein: 0, fat: 0, carbs: 100, category: 'Соусы' },
  { id: 326, name: 'Сахар коричневый', calories: 377, protein: 0, fat: 0, carbs: 97, category: 'Соусы' },
  { id: 327, name: 'Мёд', calories: 304, protein: 0, fat: 0, carbs: 82, category: 'Соусы' },
  { id: 328, name: 'Сироп кленовый', calories: 260, protein: 0, fat: 0, carbs: 67, category: 'Соусы' },
  { id: 329, name: 'Сироп шоколадный', calories: 275, protein: 1, fat: 1, carbs: 68, category: 'Соусы' },
  { id: 330, name: 'Стевия', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Соусы' },
  
  // Сладости и десерты
  { id: 331, name: 'Шоколад тёмный', calories: 546, protein: 8, fat: 31, carbs: 59, category: 'Сладости' },
  { id: 332, name: 'Шоколад молочный', calories: 535, protein: 8, fat: 30, carbs: 59, category: 'Сладости' },
  { id: 333, name: 'Шоколад белый', calories: 539, protein: 8, fat: 30, carbs: 59, category: 'Сладости' },
  { id: 334, name: 'Конфеты шоколадные', calories: 520, protein: 5, fat: 30, carbs: 55, category: 'Сладости' },
  { id: 335, name: 'Мармелад', calories: 320, protein: 0, fat: 0, carbs: 79, category: 'Сладости' },
  { id: 336, name: 'Зефир', calories: 304, protein: 1, fat: 0, carbs: 78, category: 'Сладости' },
  { id: 337, name: 'Пастила', calories: 305, protein: 1, fat: 0, carbs: 78, category: 'Сладости' },
  { id: 338, name: 'Халва', calories: 510, protein: 12, fat: 30, carbs: 50, category: 'Сладости' },
  { id: 339, name: 'Козинаки', calories: 525, protein: 12, fat: 35, carbs: 45, category: 'Сладости' },
  { id: 340, name: 'Печенье овсяное', calories: 430, protein: 7, fat: 15, carbs: 65, category: 'Сладости' },
  { id: 341, name: 'Печенье песочное', calories: 450, protein: 6, fat: 20, carbs: 65, category: 'Сладости' },
  { id: 342, name: 'Печенье галетное', calories: 390, protein: 9, fat: 10, carbs: 68, category: 'Сладости' },
  { id: 343, name: 'Вафли', calories: 480, protein: 5, fat: 25, carbs: 60, category: 'Сладости' },
  { id: 344, name: 'Пряники', calories: 350, protein: 5, fat: 5, carbs: 70, category: 'Сладости' },
  { id: 345, name: 'Торт Наполеон', calories: 380, protein: 5, fat: 22, carbs: 42, category: 'Сладости' },
  { id: 346, name: 'Торт Медовик', calories: 365, protein: 5, fat: 18, carbs: 48, category: 'Сладости' },
  { id: 347, name: 'Торт Чизкейк', calories: 320, protein: 7, fat: 22, carbs: 25, category: 'Сладости' },
  { id: 348, name: 'Пирожное Картошка', calories: 380, protein: 4, fat: 20, carbs: 48, category: 'Сладости' },
  { id: 349, name: 'Эклер', calories: 285, protein: 6, fat: 15, carbs: 32, category: 'Сладости' },
  { id: 350, name: 'Мороженое пломбир', calories: 208, protein: 3, fat: 12, carbs: 22, category: 'Сладости' },
  { id: 351, name: 'Мороженое шоколадное', calories: 216, protein: 4, fat: 11, carbs: 27, category: 'Сладости' },
  { id: 352, name: 'Мороженое фруктовое', calories: 140, protein: 1, fat: 2, carbs: 30, category: 'Сладости' },
  { id: 353, name: 'Сгущёнка', calories: 320, protein: 7, fat: 8, carbs: 56, category: 'Сладости' },
  { id: 354, name: 'Варенье клубничное', calories: 285, protein: 0, fat: 0, carbs: 72, category: 'Сладости' },
  { id: 355, name: 'Варенье малиновое', calories: 275, protein: 0, fat: 0, carbs: 70, category: 'Сладости' },
  { id: 356, name: 'Джем', calories: 265, protein: 0, fat: 0, carbs: 68, category: 'Сладости' },
  { id: 357, name: 'Повидло', calories: 245, protein: 0, fat: 0, carbs: 62, category: 'Сладости' },
  { id: 358, name: 'Шоколадная паста', calories: 540, protein: 6, fat: 30, carbs: 60, category: 'Сладости' },
  { id: 359, name: 'Арахисовая паста', calories: 588, protein: 25, fat: 50, carbs: 20, category: 'Сладости' },
  { id: 360, name: 'Нутелла', calories: 539, protein: 6, fat: 30, carbs: 57, category: 'Сладости' },
  
  // Напитки
  { id: 361, name: 'Вода', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 362, name: 'Вода минеральная', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 363, name: 'Чай чёрный без сахара', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 364, name: 'Чай зелёный без сахара', calories: 0, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 365, name: 'Чай с сахаром', calories: 28, protein: 0, fat: 0, carbs: 7, category: 'Напитки' },
  { id: 366, name: 'Кофе чёрный', calories: 2, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 367, name: 'Кофе с молоком', calories: 40, protein: 2, fat: 1, carbs: 5, category: 'Напитки' },
  { id: 368, name: 'Капучино', calories: 60, protein: 3, fat: 2, carbs: 8, category: 'Напитки' },
  { id: 369, name: 'Латте', calories: 80, protein: 4, fat: 3, carbs: 10, category: 'Напитки' },
  { id: 370, name: 'Американо', calories: 5, protein: 0, fat: 0, carbs: 1, category: 'Напитки' },
  { id: 371, name: 'Эспрессо', calories: 3, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 372, name: 'Сок апельсиновый', calories: 45, protein: 1, fat: 0, carbs: 10, category: 'Напитки' },
  { id: 373, name: 'Сок яблочный', calories: 46, protein: 0, fat: 0, carbs: 11, category: 'Напитки' },
  { id: 374, name: 'Сок томатный', calories: 21, protein: 1, fat: 0, carbs: 4, category: 'Напитки' },
  { id: 375, name: 'Сок виноградный', calories: 60, protein: 0, fat: 0, carbs: 15, category: 'Напитки' },
  { id: 376, name: 'Нектар яблочный', calories: 54, protein: 0, fat: 0, carbs: 13, category: 'Напитки' },
  { id: 377, name: 'Морс клюквенный', calories: 41, protein: 0, fat: 0, carbs: 10, category: 'Напитки' },
  { id: 378, name: 'Компот', calories: 60, protein: 0, fat: 0, carbs: 15, category: 'Напитки' },
  { id: 379, name: 'Квас', calories: 27, protein: 0, fat: 0, carbs: 5, category: 'Напитки' },
  { id: 380, name: 'Кефир 1%', calories: 40, protein: 3, fat: 1, carbs: 4, category: 'Напитки' },
  { id: 381, name: 'Ряженка 2.5%', calories: 54, protein: 3, fat: 2, carbs: 4, category: 'Напитки' },
  { id: 382, name: 'Смузи фруктовый', calories: 85, protein: 1, fat: 1, carbs: 20, category: 'Напитки' },
  { id: 383, name: 'Смузи овощной', calories: 45, protein: 2, fat: 0, carbs: 10, category: 'Напитки' },
  { id: 384, name: 'Протеиновый коктейль', calories: 95, protein: 20, fat: 1, carbs: 3, category: 'Напитки' },
  { id: 385, name: 'Энергетик', calories: 45, protein: 0, fat: 0, carbs: 11, category: 'Напитки' },
  { id: 386, name: 'Кола', calories: 42, protein: 0, fat: 0, carbs: 11, category: 'Напитки' },
  { id: 387, name: 'Спрайт', calories: 38, protein: 0, fat: 0, carbs: 9, category: 'Напитки' },
  { id: 388, name: 'Фанта', calories: 46, protein: 0, fat: 0, carbs: 12, category: 'Напитки' },
  { id: 389, name: 'Пиво светлое', calories: 43, protein: 0, fat: 0, carbs: 4, category: 'Напитки' },
  { id: 390, name: 'Пиво тёмное', calories: 48, protein: 0, fat: 0, carbs: 5, category: 'Напитки' },
  { id: 391, name: 'Вино сухое красное', calories: 70, protein: 0, fat: 0, carbs: 2, category: 'Напитки' },
  { id: 392, name: 'Вино сухое белое', calories: 66, protein: 0, fat: 0, carbs: 2, category: 'Напитки' },
  { id: 393, name: 'Вино полусладкое', calories: 88, protein: 0, fat: 0, carbs: 5, category: 'Напитки' },
  { id: 394, name: 'Шампанское', calories: 80, protein: 0, fat: 0, carbs: 4, category: 'Напитки' },
  { id: 395, name: 'Водка', calories: 235, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 396, name: 'Коньяк', calories: 239, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 397, name: 'Виски', calories: 235, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 398, name: 'Джин', calories: 231, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 399, name: 'Ром', calories: 235, protein: 0, fat: 0, carbs: 0, category: 'Напитки' },
  { id: 400, name: 'Ликёр', calories: 330, protein: 0, fat: 0, carbs: 40, category: 'Напитки' },
  
  // Фастфуд и готовая еда
  { id: 401, name: 'Биг Мак', calories: 250, protein: 13, fat: 11, carbs: 25, category: 'Фастфуд' },
  { id: 402, name: 'Чизбургер', calories: 300, protein: 15, fat: 13, carbs: 30, category: 'Фастфуд' },
  { id: 403, name: 'Двойной чизбургер', calories: 440, protein: 25, fat: 20, carbs: 35, category: 'Фастфуд' },
  { id: 404, name: 'Гамбургер', calories: 250, protein: 12, fat: 9, carbs: 30, category: 'Фастфуд' },
  { id: 405, name: 'Фишбургер', calories: 380, protein: 14, fat: 15, carbs: 45, category: 'Фастфуд' },
  { id: 406, name: 'Чикенбургер', calories: 350, protein: 18, fat: 12, carbs: 40, category: 'Фастфуд' },
  { id: 407, name: 'Шаурма', calories: 280, protein: 15, fat: 14, carbs: 28, category: 'Фастфуд' },
  { id: 408, name: 'Шаурма куриная', calories: 260, protein: 16, fat: 12, carbs: 26, category: 'Фастфуд' },
  { id: 409, name: 'Донер кебаб', calories: 290, protein: 14, fat: 16, carbs: 25, category: 'Фастфуд' },
  { id: 410, name: 'Хот-дог', calories: 320, protein: 10, fat: 18, carbs: 30, category: 'Фастфуд' },
  { id: 411, name: 'Картофель фри (малый)', calories: 230, protein: 3, fat: 11, carbs: 30, category: 'Фастфуд' },
  { id: 412, name: 'Картофель фри (средний)', calories: 340, protein: 4, fat: 16, carbs: 44, category: 'Фастфуд' },
  { id: 413, name: 'Картофель фри (большой)', calories: 450, protein: 6, fat: 22, carbs: 58, category: 'Фастфуд' },
  { id: 414, name: 'Наггетсы (6 шт)', calories: 280, protein: 14, fat: 18, carbs: 15, category: 'Фастфуд' },
  { id: 415, name: 'Куриные крылышки (6 шт)', calories: 420, protein: 24, fat: 30, carbs: 10, category: 'Фастфуд' },
  { id: 416, name: 'Ролл Филадельфия (6 шт)', calories: 320, protein: 12, fat: 15, carbs: 35, category: 'Фастфуд' },
  { id: 417, name: 'Ролл Калифорния (6 шт)', calories: 280, protein: 10, fat: 10, carbs: 38, category: 'Фастфуд' },
  { id: 418, name: 'Суши с лососем (1 шт)', calories: 45, protein: 3, fat: 1, carbs: 7, category: 'Фастфуд' },
  { id: 419, name: 'Суши с тунцом (1 шт)', calories: 40, protein: 4, fat: 1, carbs: 6, category: 'Фастфуд' },
  { id: 420, name: 'Пицца Пепперони (1 кусок)', calories: 280, protein: 12, fat: 14, carbs: 30, category: 'Фастфуд' },
  { id: 421, name: 'Пицца Маргарита (1 кусок)', calories: 250, protein: 10, fat: 10, carbs: 32, category: 'Фастфуд' },
  { id: 422, name: 'Пицца 4 сыра (1 кусок)', calories: 300, protein: 13, fat: 16, carbs: 28, category: 'Фастфуд' },
  { id: 423, name: 'Пицца Гавайская (1 кусок)', calories: 260, protein: 11, fat: 10, carbs: 35, category: 'Фастфуд' },
  { id: 424, name: 'Оливье (100г)', calories: 180, protein: 5, fat: 14, carbs: 10, category: 'Фастфуд' },
  { id: 425, name: 'Цезарь с курицей (100г)', calories: 160, protein: 12, fat: 10, carbs: 8, category: 'Фастфуд' },
  { id: 426, name: 'Греческий салат (100г)', calories: 90, protein: 3, fat: 7, carbs: 5, category: 'Фастфуд' },
  { id: 427, name: 'Винегрет (100г)', calories: 85, protein: 2, fat: 5, carbs: 10, category: 'Фастфуд' },
  { id: 428, name: 'Борщ (100г)', calories: 55, protein: 2, fat: 3, carbs: 6, category: 'Фастфуд' },
  { id: 429, name: 'Щи (100г)', calories: 45, protein: 2, fat: 2, carbs: 5, category: 'Фастфуд' },
  { id: 430, name: 'Солянка (100г)', calories: 75, protein: 4, fat: 5, carbs: 5, category: 'Фастфуд' },
  { id: 431, name: 'Харчо (100г)', calories: 85, protein: 5, fat: 5, carbs: 7, category: 'Фастфуд' },
  { id: 432, name: 'Пельмени (100г)', calories: 245, protein: 12, fat: 12, carbs: 25, category: 'Фастфуд' },
  { id: 433, name: 'Вареники с картошкой (100г)', calories: 180, protein: 5, fat: 4, carbs: 32, category: 'Фастфуд' },
  { id: 434, name: 'Вареники с творогом (100г)', calories: 190, protein: 8, fat: 5, carbs: 28, category: 'Фастфуд' },
  { id: 435, name: 'Вареники с вишней (100г)', calories: 200, protein: 4, fat: 4, carbs: 38, category: 'Фастфуд' },
  { id: 436, name: 'Блины (1 шт)', calories: 170, protein: 5, fat: 6, carbs: 25, category: 'Фастфуд' },
  { id: 437, name: 'Блины с мясом (1 шт)', calories: 200, protein: 8, fat: 8, carbs: 25, category: 'Фастфуд' },
  { id: 438, name: 'Блины с творогом (1 шт)', calories: 190, protein: 7, fat: 7, carbs: 25, category: 'Фастфуд' },
  { id: 439, name: 'Оладьи (1 шт)', calories: 150, protein: 4, fat: 6, carbs: 20, category: 'Фастфуд' },
  { id: 440, name: 'Сырники (1 шт)', calories: 220, protein: 10, fat: 10, carbs: 22, category: 'Фастфуд' },
];

// Категории продуктов
export const productCategories = [
  'Все',
  'Крупы',
  'Хлеб',
  'Мясо',
  'Рыба',
  'Морепродукты',
  'Молочное',
  'Овощи',
  'Фрукты',
  'Орехи',
  'Масла',
  'Бобовые',
  'Соусы',
  'Сладости',
  'Напитки',
  'Фастфуд',
];

// Поиск продуктов
export function searchProducts(query: string): typeof productsDatabase {
  const lowerQuery = query.toLowerCase();
  return productsDatabase.filter(p => 
    p.name.toLowerCase().includes(lowerQuery) ||
    p.category.toLowerCase().includes(lowerQuery)
  );
}

// Получение продукта по ID
export function getProductById(id: number): typeof productsDatabase[0] | undefined {
  return productsDatabase.find(p => p.id === id);
}

// Получение продуктов по категории
export function getProductsByCategory(category: string): typeof productsDatabase {
  if (category === 'Все') return productsDatabase;
  return productsDatabase.filter(p => p.category === category);
}
